### ISSUE TITLE
Why not start docker service when running in container?

### ISSUE THREAD

**Issue by TravisWhitehead** [robertdebock/ansible-role-dovecot#2]
**Describe the bug**
The `dovecot` service is not started when running in a Docker container. This means that my molecule tests for the running service will fail, instead of reflecting what I'll get in my production environment. (I test with docker but am deploying to VMs.)

**To Reproduce**
1. Run this role in a docker container (which can be done with molecule)
2. Check if `dovecot` service is running inside the container

**Expected behavior**
I would expect the dovecot service to start regardless of whether the role applies to a container, virtual machine, or bare-metal machine. 

**Error**
The `dovecot` service does not start in containers due to the [when conditional attached to the service](https://github.com/robertdebock/ansible-role-dovecot/blob/master/tasks/main.yml#L25-L26).

**Environment**
This is not relevant, as the issue stems from a logical decision in the role's task.

**Additional context**
I'm primarily wondering why the `when` conditional is present, and I think it would be helpful for it to be removed. Thank you! :)

If you agree that the `when` may be removed, I am happy to open a pull request.

**Comment by robertdebock** [comment]
You are correct, the service is not started in Docker because [systemctl does not work in Docker](https://forums.docker.com/t/systemctl-status-is-not-working-in-my-docker-container/9075)

Docker has a few limitations:
- Services can't be started.
- Reboots won't happen.
- Some files in /etc are mapped from the host to the container, like /etc/hosts

I'm working on tests on full VM's, that will take some time to implement, but at least prove that all services are configured correctly. An [initial attempt](https://github.com/robertdebock/ansible-role-bootstrap/tree/master/molecule/ec2) can be previewed.

You can already test locally using vagrant:
```
molecule test --scenario-name vagrant
```

Thanks for reporting, I'll give this role some priority in testing.

**Comment by robertdebock** [comment]
So, most Docker images I'm using (see [travis](https://github.com/robertdebock/ansible-role-dovecot/blob/master/.travis.yml)) are not capable to manage services.

I do understand that there are docker images that allow services to be managed. Maybe I can change the when into some condition that better reflects if managing a service is possible. Give me a moment to think about your request. I do see you have a point.

**Comment by robertdebock** [comment]
Hi @TravisWhitehead, have a look at that last pull request, do you think that could work for you?

**Comment by TravisWhitehead** [comment]
Thank you for clarifying that. I was overlooking the fact that docker containers usually don't manage services; upon closer examination, the docker images I was testing with were specifically installing and running systemd, and I was taking that for granted.

The PR you opened solves the problem for me and looks like a good approach. Thanks!

**Comment by robertdebock** [comment]
Just to keep you informed; I've got these tasks to do:

https://trello.com/b/K9EUrZL2/refactoring

This issue is [on there](https://trello.com/c/MDrOquAt/64-dovecot-contains-an-exclusion-for-docker-tests-by-default-except-for-molecule-copy-to-other-roles).

It looks like this will take me another couple of weeks to finish.

**Comment by TravisWhitehead** [comment]
I appreciate the update, but I think your trello board may be private.

I've cloned your branch into my playbook's `roles/` folder, so I have the solution I was hoping for. No need to rush anything on my behalf. Though I appreciate how actively you keep up on issues. :D

**Comment by robertdebock** [comment]
I've released a new version, including this request. It may take a while before Galaxy is updated; many roles have been modified.

**Comment by robertdebock** [comment]
Implemented and tested.
